service: product-service
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  profile: sandx

plugins:
  - serverless-webpack

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  PRODUCTS_DB_NAME: products
  STOCKS_DB_NAME: stocks

functions:
  getProductsList:
    handler: handlers/getProductsList.handler
    environment:
      PRODUCTS_DB_NAME: ${self:custom.PRODUCTS_DB_NAME}
      STOCKS_DB_NAME: ${self:custom.STOCKS_DB_NAME}
    events:
      - http:
          path: products
          method: get
          cors: true
  getProductsById:
    handler: handlers/getProductsById.handler
    environment:
      PRODUCTS_DB_NAME: ${self:custom.PRODUCTS_DB_NAME}
      STOCKS_DB_NAME: ${self:custom.STOCKS_DB_NAME}
    events:
      - http:
          path: products/{productId}
          method: get
          cors: true
          request:
            parameters:
              paths:
                productId: true
  createProduct:
    handler: handlers/createProduct.handler
    environment:
      PRODUCTS_DB_NAME: ${self:custom.PRODUCTS_DB_NAME}
      STOCKS_DB_NAME: ${self:custom.STOCKS_DB_NAME}
    events:
      - http:
          path: products
          method: post
          cors: true