service: import-service
frameworkVersion: '3'

custom:
  PRODUCTS_BUCKET: kalinata-import-service
  FOLDER_TO_UPLOAD: uploaded
  CATALOG_ITEMS_QUEUE_URL: https://sqs.us-east-1.amazonaws.com/012536406137/product-service-catalog-items-queue

resources:
  Resources:
    Unauthorized:
      Type: AWS::ApiGateway::GatewayResponse
      Properties:
        ResponseParameters:
          "gatewayresponse.header.Access-Control-Allow-Origin": "'*'"
          "gatewayresponse.header.Access-Control-Allow-Headers": "'*'"
        ResponseType: "DEFAULT_4XX"
        RestApiId:
          Ref: "ApiGatewayRestApi"

provider:
  name: aws
  runtime: nodejs18.x
  profile: sandx
  iam:
    role:
      statements:
        - Effect: Allow
          Action: s3:ListBucket
          Resource: arn:aws:s3:::${self:custom.PRODUCTS_BUCKET}
        - Effect: Allow
          Action: s3:*
          Resource: arn:aws:s3:::${self:custom.PRODUCTS_BUCKET}/*
        - Effect: Allow
          Action: sqs:*
          Resource: arn:aws:sqs:*:*:product-service-catalog-items-queue
  environment:
    PRODUCTS_BUCKET: ${self:custom.PRODUCTS_BUCKET}
    FOLDER_TO_UPLOAD: ${self:custom.FOLDER_TO_UPLOAD}
    CATALOG_ITEMS_QUEUE_URL: ${self:custom.CATALOG_ITEMS_QUEUE_URL}

functions:
  importProductsFile:
    handler: handlers/importProductsFile.handler
    events:
      - http:
          path: import
          method: get
          request:
            parameters:
              querystrings:
                name: true
          cors: true
          authorizer:
            type: request
            arn: arn:aws:lambda:us-east-1:012536406137:function:authorization-service-dev-basicAuthorizer
            resultTtlInSeconds: 0
  importFileParser:
    handler: handlers/importFileParser.handler
    events:
      - s3:
          bucket: ${self:custom.PRODUCTS_BUCKET}
          event: s3:ObjectCreated:*
          rules:
            - prefix: ${self:custom.FOLDER_TO_UPLOAD}/
          existing: true